### ISSUE TITLE
Cannot find module '(...)/.webpack/service/node_modules/serverless-offline-step-functions/src/state-machine-handler'

### ISSUE THREAD

**Issue by rob-verb** [flocasts/serverless-offline-step-functions#15]
I installed `serverless-offline-step-functions` and am using webpack to transpile from TypeScript to JS.  The other serverless-offline plugins are loading OK from the original `node_modules` directory (we are using webpack-node-externals to prevent the transpiler from running in the `node_modules` directory), but `serverless-offline-step-functions` seems to want to load from the `.webpack` directory.

Here is the webpack.config.js:
```
const path = require('path');
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

module.exports = {
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  externals: [nodeExternals()],
  devtool: 'source-map',
  resolve: {
    extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  target: 'node',
  plugins: [
    new ForkTsCheckerWebpackPlugin({
      async: false,
      useTypescriptIncrementalApi: true,
      memoryLimit: 4096,
    }),
  ],
  module: {
    rules: [
      // all files with a `.ts` or `.tsx` extension will be handled by `ts-loader`
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
        options: {
          transpileOnly: true,
        },
      },
    ],
  },
  stats: { warningsFilter: /\.\/middleware\// },
};
```

Here are the relevant sections of serverless.yml:
```
plugins:
  - serverless-middleware
  - serverless-offline-sqs
  - serverless-pseudo-parameters
  - serverless-s3-local
  - serverless-step-functions
  - serverless-offline-step-functions
  - serverless-vpc-plugin
  - serverless-webpack
  - serverless-offline
```

```
custom:
  serverless-offline-step-functions:
    resourcePrefix: ${self:service}-${opt:stage}-
```
```
stepFunctions:
  stateMachines:
    copyVideo:
      events:
        - http:
            path: /video/copy
            method: post
      definition:
        StartAt: Copy
        States:
          Copy:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-copyVideo
            Next: Transfer
          Transfer:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-transferVideo
            End: true
```

Here is the exact error being returned:
```
"Error: Cannot find module '/mnt/2a722e17-510c-4784-9721-7bad6328d131/Projects/verb-video-api/.webpack/service/node_modules/serverless-offline-step-functions/src/state-machine-handler'",
        "at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)",
        "at Function.Module._load (internal/modules/cjs/loader.js:591:27)",
        "at Module.require (internal/modules/cjs/loader.js:723:19)",
        "at require (internal/modules/cjs/helpers.js:14:16)",
        "at Object.createHandler (/mnt/2a722e17-510c-4784-9721-7bad6328d131/Projects/verb-video-api/node_modules/serverless-offline/src/functionHelper.js:215:15)",
        "at handler (/mnt/2a722e17-510c-4784-9721-7bad6328d131/Projects/verb-video-api/node_modules/serverless-offline/src/ApiGateway.js:485:40)",
        "at module.exports.internals.Manager.execute (/mnt/2a722e17-510c-4784-9721-7bad6328d131/Projects/verb-video-api/node_modules/@hapi/hapi/lib/toolkit.js:41:33)",
        "at Object.internals.handler (/mnt/2a722e17-510c-4784-9721-7bad6328d131/Projects/verb-video-api/node_modules/@hapi/hapi/lib/handler.js:46:48)",
        "at exports.execute (/mnt/2a722e17-510c-4784-9721-7bad6328d131/Projects/verb-video-api/node_modules/@hapi/hapi/lib/handler.js:31:36)",
        "at Request._lifecycle (/mnt/2a722e17-510c-4784-9721-7bad6328d131/Projects/verb-video-api/node_modules/@hapi/hapi/lib/request.js:312:68)"
```
Please let me know if you need more information.
