### ISSUE TITLE
Error: Lambda function not found: invoke.waitForTaskToken

### ISSUE THREAD

**Issue by karopolopoulos** [flocasts/serverless-offline-step-functions#16]
Getting the below error when calling `sls offline start --stage local`

```
  Error: Lambda function not found: invoke.waitForTaskToken
      at _.forEach (/Users/evan/Documents/telstra/repositories/tramas/node_modules/serverless-offline-step-functions/index.js:75:27)
      at /Users/evan/Documents/telstra/repositories/tramas/node_modules/lodash/lodash.js:4905:15
      at baseForOwn (/Users/evan/Documents/telstra/repositories/tramas/node_modules/lodash/lodash.js:2990:24)
      at /Users/evan/Documents/telstra/repositories/tramas/node_modules/lodash/lodash.js:4874:18
      at Function.forEach (/Users/evan/Documents/telstra/repositories/tramas/node_modules/lodash/lodash.js:9342:14)
      at _.forEach (/Users/evan/Documents/telstra/repositories/tramas/node_modules/serverless-offline-step-functions/index.js:59:11)
      at /Users/evan/Documents/telstra/repositories/tramas/node_modules/lodash/lodash.js:4905:15
      at baseForOwn (/Users/evan/Documents/telstra/repositories/tramas/node_modules/lodash/lodash.js:2990:24)
      at /Users/evan/Documents/telstra/repositories/tramas/node_modules/lodash/lodash.js:4874:18
      at Function.forEach (/Users/evan/Documents/telstra/repositories/tramas/node_modules/lodash/lodash.js:9342:14)
      at ServerlessPlugin.createEndpoints (/Users/evan/Documents/telstra/repositories/tramas/node_modules/serverless-offline-step-functions/index.js:54:7)
      at <anonymous>
```

Found that the Task Resource `arn:aws:states:::lambda:invoke.waitForTaskToken` is not handled.
Here is my state machine config:
```
transitionElrod:
  name: transition-elrod-${self:service}-${self:provider.stage}
  role:
    'Fn::GetAtt':
      - StateMachineIAMRole
      - Arn
  definition:
    StartAt: GateA
    States:
      GateA:
        Type: Choice
        Choices:
          - And:
              - Or:
                  - Variable: '$.metadata.action'
                    StringEquals: 'disconnect'
                  - Variable: '$.metadata.action'
                    StringEquals: 'network-disconnect'
              - Variable: '$.metadata.discoveredState'
                BooleanEquals: true
            Next: DisconnectInitialise
          - Variable: '$.metadata.action'
            StringEquals: 'rollback'
            Next: RollbackInitialise
          - Or:
              - Variable: '$.metadata.action'
                StringEquals: 'discover'
              - Variable: '$.metadata.action'
                StringEquals: 'validate'
              - Variable: '$.metadata.action'
                StringEquals: 'reserve'
              - Variable: '$.metadata.action'
                StringEquals: 'disconnect'
              - Variable: '$.metadata.action'
                StringEquals: 'network-disconnect'
            Next: DiscoverInitialise
        Default: UnhandledChoice
      DiscoverInitialise:
        Type: Task
        Resource: arn:aws:states:::lambda:invoke.waitForTaskToken
        Parameters:
          FunctionName: ${self:custom.config.project}-${self:provider.stage}-discover-initialise
          Payload:
            metadata:
              transitionId.$: $.metadata.transitionId
              executionId.$: $.metadata.executionId
              auxiliaryResourceIds.$: $.metadata.auxiliaryResourceIds
              discoveredState.$: $.metadata.discoveredState
              action.$: $.metadata.action
              taskToken.$: $$.Task.Token
        Next: DiscoverFinalise
      DiscoverFinalise:
        Type: Task
        Resource: arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-discover-finalise
        Next: GateB
      GateB:
        Type: Choice
        Choices:
          - Or:
              - Variable: '$.metadata.action'
                StringEquals: 'disconnect'
              - Variable: '$.metadata.action'
                StringEquals: 'network-disconnect'
            Next: DisconnectInitialise
          - Variable: '$.metadata.action'
            StringEquals: 'reserve'
            Next: Validate
          - Variable: '$.metadata.action'
            StringEquals: 'validate'
            Next: Validate
        Default: UnhandledChoice
      Validate:
        Type: Task
        Resource: arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-validate
        Next: GateC
      GateC:
        Type: Choice
        Choices:
          - Variable: '$.metadata.action'
            StringEquals: 'validate'
            Next: Completed
          - Variable: '$.metadata.action'
            StringEquals: 'reserve'
            Next: ReserveInitialise
        Default: UnhandledChoice
      RollbackInitialise:
        Type: Task
        Resource: arn:aws:states:::lambda:invoke.waitForTaskToken
        Parameters:
          FunctionName: ${self:custom.config.project}-${self:provider.stage}-rollback-initialise
          Payload:
            metadata:
              transitionId.$: $.metadata.transitionId
              executionId.$: $.metadata.executionId
              auxiliaryResourceIds.$: $.metadata.auxiliaryResourceIds
              discoveredState.$: $.metadata.discoveredState
              action.$: $.metadata.action
              taskToken.$: $$.Task.Token
        Next: RollbackFinalise
      RollbackFinalise:
        Type: Task
        Resource: arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-rollback-finalise
        Next: Completed
      ReserveInitialise:
        Type: Task
        Resource: arn:aws:states:::lambda:invoke.waitForTaskToken
        Parameters:
          FunctionName: ${self:custom.config.project}-${self:provider.stage}-reserve-initialise
          Payload:
            metadata:
              transitionId.$: $.metadata.transitionId
              executionId.$: $.metadata.executionId
              auxiliaryResourceIds.$: $.metadata.auxiliaryResourceIds
              discoveredState.$: $.metadata.discoveredState
              action.$: $.metadata.action
              taskToken.$: $$.Task.Token
        Next: ReserveFinalise
      ReserveFinalise:
        Type: Task
        Resource: arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-reserve-finalise
        Next: Completed
      DisconnectInitialise:
        Type: Task
        Resource: arn:aws:states:::lambda:invoke.waitForTaskToken
        Parameters:
          FunctionName: ${self:custom.config.project}-${self:provider.stage}-disconnect-initialise
          Payload:
            metadata:
              transitionId.$: $.metadata.transitionId
              executionId.$: $.metadata.executionId
              auxiliaryResourceIds.$: $.metadata.auxiliaryResourceIds
              discoveredState.$: $.metadata.discoveredState
              action.$: $.metadata.action
              taskToken.$: $$.Task.Token
        Next: DisconnectFinalise
      DisconnectFinalise:
        Type: Task
        Resource: arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-disconnect-finalise
        Next: Completed
      Completed:
        Type: Succeed
      UnhandledChoice:
        Type: Fail
```
